-- generated by ddljen
-- target database: mysql 

	 drop table if exists ref_alert_risk_levels; 	create table ref_alert_risk_levels (
			arl_id   integer  (18 )		 auto_increment 						 ,			name   varchar  (30 )				 not null					 ,			descr   text 												,constraint arl_pk primary key (
					arl_id
							)
				,constraint arl_name_un unique (
					name
							)
		);
	 drop table if exists ref_alert_status; 	create table ref_alert_status (
			ast_id   integer  (18 )		 auto_increment 						 ,			name   varchar  (30 )				 not null					 ,			descr   text 												,constraint ast_pk primary key (
					ast_id
							)
				,constraint ast_name_un unique (
					name
							)
		);
	 drop table if exists alerts; 	create table alerts (
			alt_id   integer  (18 )		 auto_increment 						 ,			ade_id   integer  (18 )				 not null					 ,			ast_id   integer  (18 )				 not null					 ,			arl_id   integer  (18 )				 not null					 ,			creation_time   timestamp 				 not null					 ,			origin_value   varchar  (51 )												,constraint alt_pk primary key (
					alt_id
							)
			);

					alter table alerts add (
					constraint alt_ast_fk
		   	foreign key (ast_id)
			references ref_alert_status (ast_id)
						 ,					constraint alt_arl_fk
		   	foreign key (arl_id)
			references ref_alert_risk_levels (arl_id)
										);
	
	create view v1 as select * from events;	
	create view v1 as select * from events;	

